language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mkrzek15/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run -e CI=true mkrzek15/react-test npm test

after_success:
  - docker build -t mkrzek15/multi-client ./client
  - docker build -t mkrzek15/multi-nginx  ./nginx
  - docker build -t mkrzek15/multi-server ./server
  - docker build -t mkrzek15/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mkrzek15/multi-client
  - docker push mkrzek15/multi-nginx
  - docker push mkrzek15/multi-server
  - docker push mkrzek15/multi-worker
